FROM ghcr.io/open-webui/open-webui:main

RUN pip install --no-cache-dir "langfuse>=2,<3"

COPY backend/open_webui/nemo_guardrails/ /app/backend/open_webui/nemo_guardrails/

COPY backend/open_webui/utils/guardrails.py /app/backend/open_webui/utils/guardrails.py
COPY backend/open_webui/utils/chat.py /app/backend/open_webui/utils/chat.py
